import "./globals.css";
import '../scss/main.scss';
import Header from "@/components/header";
import Footer from "@/components/footer";
import "swiper/css";
export const metadata = {
  title: "SEA GLOBAL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script type="module" src="https://widgets.tradingview-widget.com/w/en/tv-ticker-tape.js"></script>
      </head>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
